# Generated by Django 4.2.14 on 2024-07-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_posts', '0003_outfitpost_items'),
        ('scraps', '0001_initial'),
        ('users', '0001_initial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='outfit_item_scraps',
            field=models.ManyToManyField(through='scraps.OutfitItemScrap', to='outfit_posts.outfititem'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='outfit_post_scraps',
            field=models.ManyToManyField(through='scraps.OutfitPostScrap', to='outfit_posts.outfitpost'),
        ),
    ]
