# Generated by Django 4.2.14 on 2024-10-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_image_url',
            new_name='profile_image',
        ),
    ]
