services:
  django_app:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --log-config /config/uvicorn_log.ini
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./gunicorn/uvicorn_log.ini:/config/uvicorn_log.ini
      - ./logs:/logs
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
