# Generated by Django 4.2.14 on 2024-07-28 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('celebrities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('MALE', '남성'), ('FEMALE', '여성'), ('UNISEX', '공용')], max_length=10)),
                ('image_url', models.CharField(max_length=300)),
                ('celebrity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebrities.celebrity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
