# Generated by Django 4.2.14 on 2024-07-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_posts', '0002_outfititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitpost',
            name='items',
            field=models.ManyToManyField(to='outfit_posts.outfititem'),
        ),
    ]
