# Generated by Django 4.2.14 on 2024-07-28 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_posts', '0003_outfitpost_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outfititem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='outfitpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='outfititem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
