# Generated by Django 4.2.14 on 2024-07-28 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
        ('celebrities', '0001_initial'),
        ('outfit_posts', '0004_alter_outfititem_options_alter_outfitpost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfititem',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_items', to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='outfitpost',
            name='celebrity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_posts', to='celebrities.celebrity'),
        ),
        migrations.AlterField(
            model_name='outfitpost',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
