# Generated by Django 4.2.14 on 2024-07-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_posts', '0006_alter_outfititem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfititem',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='outfitpost',
            old_name='celebrity_id',
            new_name='celebrity',
        ),
        migrations.RenameField(
            model_name='outfitpost',
            old_name='created_by',
            new_name='creator',
        ),
    ]
