# Generated by Django 4.2.14 on 2024-07-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_posts', '0007_rename_brand_id_outfititem_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitpost',
            name='gender',
            field=models.CharField(choices=[('남성', '남성'), ('여성', '여성'), ('공용', '공용')], max_length=10),
        ),
    ]
