# Generated by Django 4.2.14 on 2024-08-21 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_posts', '0008_alter_outfitpost_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitPostItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfititem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfit_posts.outfititem')),
                ('outfitpost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfit_posts.outfitpost')),
            ],
        ),
        migrations.RemoveField(
            model_name='outfitpost',
            name='items',
        ),
        migrations.AddField(
            model_name='outfitpost',
            name='items',
            field=models.ManyToManyField(through='outfit_posts.OutfitPostItems', to='outfit_posts.outfititem'),
        ),
    ]
