# Generated by Django 4.2.14 on 2024-08-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_posts', '0009_outfitpostitems_alter_outfitpost_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfitpostitems',
            old_name='outfititem_id',
            new_name='outfit_item',
        ),
        migrations.RenameField(
            model_name='outfitpostitems',
            old_name='outfitpost_id',
            new_name='outfit_post',
        ),
    ]
