# Generated by Django 4.2.14 on 2024-08-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_posts', '0011_alter_outfitpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitpost',
            name='image',
            field=models.ImageField(default=' ', upload_to='outfit-post'),
            preserve_default=False,
        ),
    ]
