# Generated by Django 4.2.14 on 2024-08-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_posts', '0012_outfitpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfitpost',
            name='image_url',
        ),
    ]
