# Generated by Django 4.2.14 on 2024-08-27 07:37

import django.core.validators
from django.db import migrations, models
import outfit_posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_posts', '0014_alter_outfitpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfititem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='outfititem',
            name='image',
            field=models.ImageField(default=' ', upload_to=outfit_posts.models.generate_outfit_item_image_filename, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'jfif', 'png', 'bmp', 'webp', 'tif', 'tiff'])]),
            preserve_default=False,
        ),
    ]
