# Generated by Django 4.2.14 on 2024-08-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_posts', '0015_remove_outfititem_image_url_outfititem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfititem',
            name='category',
            field=models.CharField(choices=[('상의', '상의'), ('하의', '하의'), ('아우터', '아우터'), ('신발', '신발'), ('가방', '가방'), ('악세사리', '악세사리'), ('기타', '기타')], max_length=10),
        ),
    ]
