# Generated by Django 4.2.14 on 2024-08-27 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_posts', '0016_alter_outfititem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfititem',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='outfitpost',
            name='title',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
