# Generated by Django 4.2.14 on 2024-07-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outfititemscrap',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='outfitpostscrap',
            options={'ordering': ['-created_at']},
        ),
    ]
