# Generated by Django 4.2.14 on 2024-07-28 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_posts', '0005_alter_outfititem_brand_id_and_more'),
        ('scraps', '0002_alter_outfititemscrap_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfititemscrap',
            name='outfit_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='outfit_posts.outfititem'),
        ),
        migrations.AlterField(
            model_name='outfitpostscrap',
            name='outfit_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='outfit_posts.outfitpost'),
        ),
    ]
