# Generated by Django 4.2.14 on 2024-07-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0003_celebrity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='category',
            field=models.CharField(choices=[('아이돌', '아이돌'), ('모델', '모델'), ('가수', '가수'), ('배우', '배우'), ('인플루언서', '인플루언서'), ('기타', '기타')], max_length=10),
        ),
    ]
