name: deploy
on:
  push:
    branches: ["master"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: AWS Credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Github action IP 가져오기
        id: publicip
        run: |
          response=$(curl -s canhazip.com)
          echo "ip=$response" >> "$GITHUB_OUTPUT"

      - name: Github Actions IP를 EC2 Security Group에 추가
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_EC2_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port ${{ secrets.AWS_EC2_SSH_PORT }} \
            --cidr ${{ steps.publicip.outputs.ip }}/32

      - name: SSH로 EC2에 접근해서 배포 작업 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          port: ${{ secrets.AWS_EC2_SSH_PORT }}
          script: |
            cd ~/backend
            git pull origin master
            echo "${{ secrets.ENV }}" > .env
            docker compose down --rmi all
            docker compose up --build -d

      - name: EC2 Security Group에 추가 했던 Github Actions IP 제거
        if: ${{ always() }}
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_EC2_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port ${{ secrets.AWS_EC2_SSH_PORT }} \
            --cidr ${{ steps.publicip.outputs.ip }}/32
